services:
  mysql:
    image: debezium/example-mysql:1.1
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    volumes:
      # - ./mysql/data:/var/lib/mysql
      - ./sql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  jobmanager:
    user: flink:flink
    image: flink:1.20
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./jobs/job.sql:/opt/flink/jobs/job.sql
      - ./jars:/opt/flink/lib/plugins
      - shared-tmpfs:/tmp/iceberg
    deploy:
          replicas: 1
  taskmanager:
    user: flink:flink
    image: flink:1.20
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./jars:/opt/flink/lib/plugins
      - shared-tmpfs:/tmp/iceberg
    deploy:
          replicas: 2

volumes:
  shared-tmpfs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"